### Welcome Message
GET http://localhost:8000/

### GET all the students
GET http://localhost:8000/students
Accept: application/json

### GET a student by id
GET http://localhost:8000/students/1
Accept: application/json

### POST create a new student
POST http://localhost:8000/students
Content-Type: application/json

{
  "studentName": "Charlie",
  "age": 22
}

### PUT update an existing student by id
PUT http://localhost:8000/students/1
Content-Type: application/json

{
  "studentName": "Alice Updated",
  "age": 26
}

### DELETE delete an existing student by id
DELETE http://localhost:8000/students/3